### ISSUE TITLE
virtual env installation

### ISSUE THREAD

**Issue by jubeschi** [exmorse/pyRadioHeadNRF24#1]
Hello,

Hope you don't mind if I raise an issue here to get your support.

I would really like to use your python wrapper on Raspberry PI but I am having troubles installing the cffi library in virtual environment.
_pi@pimaster:~/tlaloc $ python ../download/pyRadioHeadNRF24-master/examples/reliable_datagram_server.py 
Traceback (most recent call last):
  File "../download/pyRadioHeadNRF24-master/examples/reliable_datagram_server.py", line 8, in <module>
    import pyRadioHeadNRF24 as radio
  File "/home/pi/download/pyRadioHeadNRF24-master/pyRadioHeadNRF24.py", line 3, in <module>
    from cffi import FFI
ImportError: No module named cffi_

Trying to install cffi with pip 
venv/bin/pip install cffi
gives me this error:

_Command /home/pi/tlaloc/venv/bin/python2 -c "import setuptools, tokenize;__file__='/tmp/pip-build-hf8YBc/cffi/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-oBaOuD-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/pi/tlaloc/venv/include/site/python2.7 failed with error code 1 in /tmp/pip-build-hf8YBc/cffi_

Thanks a lot in advance for your help.

**Comment by exmorse** [comment]
I tried to re-create your situation and i was able to install `cffi` in a virtual environment. 

I suggest you to install `libffi-dev` and `python-dev` from the package manager and then try again.
Hope this helps.

**Comment by jubeschi** [comment]
Thank you so much for your prompt reply.
`apt-get update`, and `apt-get install python.dev`. Once done that the pip installation of cffi went fine. I will now try to run the example.

**Comment by jubeschi** [comment]
Update: running the examples I get a segmentation fault before the startup. Any clue? Both examples gives the same result.

**Comment by exmorse** [comment]
Probably that happens because you need root permissions.
Try to launch the examples with `sudo`.

**Comment by jubeschi** [comment]
In fact, with sudo the server starts correctly, thanks again!

Now the problem I have is that the arduino sending the reliable datagram (from the rh example) fails, and nothing is received on the PI. I posted here also:
https://groups.google.com/forum/#!topic/radiohead-arduino/S27J72u1PS0
